
spring:
  application:
    name: eureka-server
server:
  port: ${PORT:8761}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
    register-with-eureka: false
    fetch-registry: false

